import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import Drawer from './components/Drawer';

function Home(){
return(
  <div style={{display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',width:'50%',height:'auto',marginTop:70,marginBottom:70,background:'lightblue'}}>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc est lacus, consectetur a magna eu, cursus blandit enim. Nulla facilisis mauris nec gravida mollis. Aliquam hendrerit ultricies sem sed mollis. Pellentesque at accumsan mauris. Nullam in nulla velit. Phasellus sed purus sit amet ipsum lobortis aliquet eu eget turpis. Fusce luctus lobortis quam, id vulputate dolor ultrices a. Pellentesque accumsan est nisi, eget facilisis neque elementum eget. Morbi eget augue dui. Mauris et euismod libero. Cras quis aliquam purus, vitae euismod risus.

  Vivamus metus leo, euismod id velit nec, pulvinar pulvinar ante. Mauris at risus et enim hendrerit venenatis non quis elit. Fusce pretium dignissim ex, iaculis iaculis mauris iaculis tincidunt. Vivamus a lorem sed ex viverra pretium. Aenean consectetur suscipit odio, at tristique ligula tempus non. Donec vehicula erat quis venenatis tincidunt. Suspendisse ut accumsan libero. Ut nec auctor purus, a cursus urna. Nam eget metus erat. Integer blandit tempus egestas. Cras non blandit urna. Praesent ac urna vulputate, ornare lorem sollicitudin, pharetra enim. Fusce sit amet mi enim. Nam mattis diam ligula, eget blandit odio vulputate pretium. Nunc consectetur enim eget lectus accumsan, a scelerisque sem vulputate. Ut sit amet neque nisl.

  Aenean non mollis quam. Sed porttitor, lorem at vulputate semper, odio sapien eleifend felis, sit amet venenatis enim est in leo. Praesent ut rutrum nunc. Sed posuere a nisi et sagittis. Pellentesque quis dolor nisl. Vestibulum scelerisque nulla ut dui hendrerit, vel lobortis risus consequat. Donec porttitor tincidunt commodo. Ut ultricies ante vel neque eleifend aliquam. Integer consequat at tortor quis iaculis. Sed malesuada eget felis quis auctor. Vivamus in congue ipsum. Donec vulputate lacus augue. Etiam dapibus massa ac aliquet fermentum.

  Praesent a dictum ipsum. Quisque eget felis ultricies felis condimentum semper. Aliquam non nunc vel dolor volutpat tincidunt sit amet ac tortor. Donec viverra dolor at ultricies convallis. Nullam tincidunt tristique convallis. Etiam quis eros scelerisque, porttitor odio et, pretium tellus. Aliquam id varius dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus leo dolor, cursus sed ex vel, semper tempor felis. Fusce pellentesque nisl mi, et vestibulum tellus sodales ac. Pellentesque lacinia, erat ultrices feugiat porta, velit odio sagittis velit, nec luctus ante libero egestas est.

  Morbi volutpat leo nunc, finibus imperdiet quam vehicula at. Proin maximus magna ante, sagittis semper quam porta non. Mauris porttitor nulla nisi, sed maximus purus ultrices vitae. Nullam maximus aliquam tortor, ut mollis ipsum efficitur non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eu cursus ipsum, in viverra massa. Quisque egestas, diam sit amet ullamcorper fermentum, lacus risus porta massa, eu efficitur velit sem at elit. Suspendisse ornare quis justo feugiat condimentum. Morbi nec suscipit dolor, id malesuada quam. Cras scelerisque ipsum ipsum, in posuere neque semper ut. Morbi in nisl et elit scelerisque congue. Duis interdum pulvinar felis id suscipit. Mauris tincidunt tincidunt facilisis. Suspendisse fringilla sapien ac quam convallis, tempor sollicitudin lectus porttitor. Donec consequat at libero sit amet laoreet.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc est lacus, consectetur a magna eu, cursus blandit enim. Nulla facilisis mauris nec gravida mollis. Aliquam hendrerit ultricies sem sed mollis. Pellentesque at accumsan mauris. Nullam in nulla velit. Phasellus sed purus sit amet ipsum lobortis aliquet eu eget turpis. Fusce luctus lobortis quam, id vulputate dolor ultrices a. Pellentesque accumsan est nisi, eget facilisis neque elementum eget. Morbi eget augue dui. Mauris et euismod libero. Cras quis aliquam purus, vitae euismod risus.

Vivamus metus leo, euismod id velit nec, pulvinar pulvinar ante. Mauris at risus et enim hendrerit venenatis non quis elit. Fusce pretium dignissim ex, iaculis iaculis mauris iaculis tincidunt. Vivamus a lorem sed ex viverra pretium. Aenean consectetur suscipit odio, at tristique ligula tempus non. Donec vehicula erat quis venenatis tincidunt. Suspendisse ut accumsan libero. Ut nec auctor purus, a cursus urna. Nam eget metus erat. Integer blandit tempus egestas. Cras non blandit urna. Praesent ac urna vulputate, ornare lorem sollicitudin, pharetra enim. Fusce sit amet mi enim. Nam mattis diam ligula, eget blandit odio vulputate pretium. Nunc consectetur enim eget lectus accumsan, a scelerisque sem vulputate. Ut sit amet neque nisl.

Aenean non mollis quam. Sed porttitor, lorem at vulputate semper, odio sapien eleifend felis, sit amet venenatis enim est in leo. Praesent ut rutrum nunc. Sed posuere a nisi et sagittis. Pellentesque quis dolor nisl. Vestibulum scelerisque nulla ut dui hendrerit, vel lobortis risus consequat. Donec porttitor tincidunt commodo. Ut ultricies ante vel neque eleifend aliquam. Integer consequat at tortor quis iaculis. Sed malesuada eget felis quis auctor. Vivamus in congue ipsum. Donec vulputate lacus augue. Etiam dapibus massa ac aliquet fermentum.

Praesent a dictum ipsum. Quisque eget felis ultricies felis condimentum semper. Aliquam non nunc vel dolor volutpat tincidunt sit amet ac tortor. Donec viverra dolor at ultricies convallis. Nullam tincidunt tristique convallis. Etiam quis eros scelerisque, porttitor odio et, pretium tellus. Aliquam id varius dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus leo dolor, cursus sed ex vel, semper tempor felis. Fusce pellentesque nisl mi, et vestibulum tellus sodales ac. Pellentesque lacinia, erat ultrices feugiat porta, velit odio sagittis velit, nec luctus ante libero egestas est.

Morbi volutpat leo nunc, finibus imperdiet quam vehicula at. Proin maximus magna ante, sagittis semper quam porta non. Mauris porttitor nulla nisi, sed maximus purus ultrices vitae. Nullam maximus aliquam tortor, ut mollis ipsum efficitur non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eu cursus ipsum, in viverra massa. Quisque egestas, diam sit amet ullamcorper fermentum, lacus risus porta massa, eu efficitur velit sem at elit. Suspendisse ornare quis justo feugiat condimentum. Morbi nec suscipit dolor, id malesuada quam. Cras scelerisque ipsum ipsum, in posuere neque semper ut. Morbi in nisl et elit scelerisque congue. Duis interdum pulvinar felis id suscipit. Mauris tincidunt tincidunt facilisis. Suspendisse fringilla sapien ac quam convallis, tempor sollicitudin lectus porttitor. Donec consequat at libero sit amet laoreet.


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc est lacus, consectetur a magna eu, cursus blandit enim. Nulla facilisis mauris nec gravida mollis. Aliquam hendrerit ultricies sem sed mollis. Pellentesque at accumsan mauris. Nullam in nulla velit. Phasellus sed purus sit amet ipsum lobortis aliquet eu eget turpis. Fusce luctus lobortis quam, id vulputate dolor ultrices a. Pellentesque accumsan est nisi, eget facilisis neque elementum eget. Morbi eget augue dui. Mauris et euismod libero. Cras quis aliquam purus, vitae euismod risus.

Vivamus metus leo, euismod id velit nec, pulvinar pulvinar ante. Mauris at risus et enim hendrerit venenatis non quis elit. Fusce pretium dignissim ex, iaculis iaculis mauris iaculis tincidunt. Vivamus a lorem sed ex viverra pretium. Aenean consectetur suscipit odio, at tristique ligula tempus non. Donec vehicula erat quis venenatis tincidunt. Suspendisse ut accumsan libero. Ut nec auctor purus, a cursus urna. Nam eget metus erat. Integer blandit tempus egestas. Cras non blandit urna. Praesent ac urna vulputate, ornare lorem sollicitudin, pharetra enim. Fusce sit amet mi enim. Nam mattis diam ligula, eget blandit odio vulputate pretium. Nunc consectetur enim eget lectus accumsan, a scelerisque sem vulputate. Ut sit amet neque nisl.

Aenean non mollis quam. Sed porttitor, lorem at vulputate semper, odio sapien eleifend felis, sit amet venenatis enim est in leo. Praesent ut rutrum nunc. Sed posuere a nisi et sagittis. Pellentesque quis dolor nisl. Vestibulum scelerisque nulla ut dui hendrerit, vel lobortis risus consequat. Donec porttitor tincidunt commodo. Ut ultricies ante vel neque eleifend aliquam. Integer consequat at tortor quis iaculis. Sed malesuada eget felis quis auctor. Vivamus in congue ipsum. Donec vulputate lacus augue. Etiam dapibus massa ac aliquet fermentum.

Praesent a dictum ipsum. Quisque eget felis ultricies felis condimentum semper. Aliquam non nunc vel dolor volutpat tincidunt sit amet ac tortor. Donec viverra dolor at ultricies convallis. Nullam tincidunt tristique convallis. Etiam quis eros scelerisque, porttitor odio et, pretium tellus. Aliquam id varius dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus leo dolor, cursus sed ex vel, semper tempor felis. Fusce pellentesque nisl mi, et vestibulum tellus sodales ac. Pellentesque lacinia, erat ultrices feugiat porta, velit odio sagittis velit, nec luctus ante libero egestas est.

Morbi volutpat leo nunc, finibus imperdiet quam vehicula at. Proin maximus magna ante, sagittis semper quam porta non. Mauris porttitor nulla nisi, sed maximus purus ultrices vitae. Nullam maximus aliquam tortor, ut mollis ipsum efficitur non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eu cursus ipsum, in viverra massa. Quisque egestas, diam sit amet ullamcorper fermentum, lacus risus porta massa, eu efficitur velit sem at elit. Suspendisse ornare quis justo feugiat condimentum. Morbi nec suscipit dolor, id malesuada quam. Cras scelerisque ipsum ipsum, in posuere neque semper ut. Morbi in nisl et elit scelerisque congue. Duis interdum pulvinar felis id suscipit. Mauris tincidunt tincidunt facilisis. Suspendisse fringilla sapien ac quam convallis, tempor sollicitudin lectus porttitor. Donec consequat at libero sit amet laoreet.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc est lacus, consectetur a magna eu, cursus blandit enim. Nulla facilisis mauris nec gravida mollis. Aliquam hendrerit ultricies sem sed mollis. Pellentesque at accumsan mauris. Nullam in nulla velit. Phasellus sed purus sit amet ipsum lobortis aliquet eu eget turpis. Fusce luctus lobortis quam, id vulputate dolor ultrices a. Pellentesque accumsan est nisi, eget facilisis neque elementum eget. Morbi eget augue dui. Mauris et euismod libero. Cras quis aliquam purus, vitae euismod risus.

Vivamus metus leo, euismod id velit nec, pulvinar pulvinar ante. Mauris at risus et enim hendrerit venenatis non quis elit. Fusce pretium dignissim ex, iaculis iaculis mauris iaculis tincidunt. Vivamus a lorem sed ex viverra pretium. Aenean consectetur suscipit odio, at tristique ligula tempus non. Donec vehicula erat quis venenatis tincidunt. Suspendisse ut accumsan libero. Ut nec auctor purus, a cursus urna. Nam eget metus erat. Integer blandit tempus egestas. Cras non blandit urna. Praesent ac urna vulputate, ornare lorem sollicitudin, pharetra enim. Fusce sit amet mi enim. Nam mattis diam ligula, eget blandit odio vulputate pretium. Nunc consectetur enim eget lectus accumsan, a scelerisque sem vulputate. Ut sit amet neque nisl.

Aenean non mollis quam. Sed porttitor, lorem at vulputate semper, odio sapien eleifend felis, sit amet venenatis enim est in leo. Praesent ut rutrum nunc. Sed posuere a nisi et sagittis. Pellentesque quis dolor nisl. Vestibulum scelerisque nulla ut dui hendrerit, vel lobortis risus consequat. Donec porttitor tincidunt commodo. Ut ultricies ante vel neque eleifend aliquam. Integer consequat at tortor quis iaculis. Sed malesuada eget felis quis auctor. Vivamus in congue ipsum. Donec vulputate lacus augue. Etiam dapibus massa ac aliquet fermentum.

Praesent a dictum ipsum. Quisque eget felis ultricies felis condimentum semper. Aliquam non nunc vel dolor volutpat tincidunt sit amet ac tortor. Donec viverra dolor at ultricies convallis. Nullam tincidunt tristique convallis. Etiam quis eros scelerisque, porttitor odio et, pretium tellus. Aliquam id varius dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus leo dolor, cursus sed ex vel, semper tempor felis. Fusce pellentesque nisl mi, et vestibulum tellus sodales ac. Pellentesque lacinia, erat ultrices feugiat porta, velit odio sagittis velit, nec luctus ante libero egestas est.

Morbi volutpat leo nunc, finibus imperdiet quam vehicula at. Proin maximus magna ante, sagittis semper quam porta non. Mauris porttitor nulla nisi, sed maximus purus ultrices vitae. Nullam maximus aliquam tortor, ut mollis ipsum efficitur non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eu cursus ipsum, in viverra massa. Quisque egestas, diam sit amet ullamcorper fermentum, lacus risus porta massa, eu efficitur velit sem at elit. Suspendisse ornare quis justo feugiat condimentum. Morbi nec suscipit dolor, id m
  </div>

)

}


ReactDOM.render(
  <React.StrictMode>
    <Drawer
    routes={[{url:"/",component:<Home/>,label:"Home"},{url:"/shop",component:<h1>About</h1>,label:"Shop"}]}
    mainContainerStyles={{display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',width:'100%',height:'100%'}}
    hamburgerIconColor='red'
    drawerCloseColor='orange'
    drawerBackgroundColor='blue'
    drawerLabelsStyle={{border:'2.5px solid orange',width:'auto',color:'orange',fontFamily:'monospace',padding:12,margin:2}}
    />
  </React.StrictMode>,
  document.getElementById('root')
);
